project:
  type: website
  output-dir: docs

website:
  title: "Moritz Schwarz"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: cv.pdf
        text: CV
      - research.qmd
      - teaching.qmd        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



