# project settings
project:
  type: website
  output-dir: docs

# website settings
website:
  title: "Moritz Schwarz"
  description: "My personal website"
  # image: images/logo.png
  # favicon: images/logo.png

  navbar:
    # logo: images/logo.png
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - href: cv.pdf
        text: CV
      - research.qmd
      - teaching.qmd        
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Moritz Schwarz</span>
    # center: |
    #   <span class="faux-block"><a </a></span>
    # right: |
    #   <span class="faux-block"><a </a></span>
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



