# project settings
project:
  type: website
  output-dir: docs

# website settings
website:
  title: "Moritz Schwarz"
  description: "I am a PhD candidate in Economics at the University of Vienna. My research interests include Empirical Industrial Organization and Competition Economics."
  # image: images/logo.png
  # favicon: images/logo.png
  # navigation bar and sections
  navbar:
    # logo: images/logo.png
    pinned: true
    right:
      - text: Home
        href: index.qmd
      - text: CV
        href: cv/cv.pdf
        #target: cv/cv.pdf
      - text: Research  
        href: research/index.qmd
      - text: Teaching
        href: teaching/index.qmd        
      # - text: Policy
      #   href: policy/index.qmd 
      #- icon: rss
      #  href: index.xml
  search: true
  # footer settings
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Moritz Schwarz</span>
    #background: light
    # center: |
    #   <span class="faux-block"><a </a></span>
    # right: |
    #   <span class="faux-block"><a </a></span>
  back-to-top-navigation: true

### Format Settings
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

# potentially useful settings 
# RSS settings    https://quarto.org/docs/websites/website-blog.html
# listing: feed
#     title: Moritz Schwarz
#     description: New Research by Moritz Schwarz 
#     language: en

#       preview: 
#     port: 22222
#     browser: true
#     watch-inputs: true
#     navigate: true

# execute:
#   freeze: true

# format:
#   html:
#     fontsize: 1.1em
#     theme: 
#       - pulse
#       - html/styles.scss
#     toc: false
#     code-link: true
#     anchor-sections: true
#     fig-cap-location: margin
#     reference-location: margin
#     footnotes-hover: true